//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Repository_Unity_Injection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string EmpGender { get; set; }
        public string EmpCountry { get; set; }
        public Nullable<System.DateTime> EmpEnteredOn { get; set; }
    }
}
